.TH keybindings-exim 1 25/06/2016 "Fluxability Project"
.SH NAME
.B 
keybindings-exim \-
.BR
.SH SYNOPSIS
.BR
.SH DESCRIPTION
.P
.BR
.SH OPTIONS
.BR
.BR
.SH EXIT CODES
.BR
.SH FILES
.I
.RS
.RE
.BR
.SH BUGS
.BR
.SH AUTHOR
keybindings-exim was written by B.H.
     B.H. wrote this manpage.
.BR
.SH WEBSITE
https://github.com/burt1iband/keybindings_exim-gs
.BR
.SH SEE ALSO
.BR
